server:
  port: 80

eureka:
  client:
    register-with-eureka: true #是否将自己注册进eureka server
    fetch-registry: true #是否从eureka server抓取已有的注册信息，单节点不影响，集群必须设置为true配合ribbon使用负载均衡
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
spring:
  application:
    name: cloud-order-service