server:
  port: 80
spring:
  application:
    name: consul-provider-order
  #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
#        heartbeat:
#          enabled: true
#        prefer-ip-address: true #使用docker consul服务端需要加这个